create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  lead_key text not null unique,
  platform text,
  lead_source text,
  source_id text,
  post_id text,
  group_id text,
  post_url text,
  comment_id text,
  comment_url text,
  customer_name text,
  customer_phone text,
  phones jsonb not null default '[]'::jsonb,
  customer_need text,
  intent text,
  product_or_service text,
  location text,
  budget text,
  urgency text,
  contact_status text,
  confidence numeric,
  evidence text,
  raw_lead jsonb not null default '{}'::jsonb,
  created_by_staff_id text,
  created_by_staff_name text,
  created_by_staff_username text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_post_id_idx
  on public.leads (post_id);

create index if not exists leads_customer_phone_idx
  on public.leads (customer_phone);

create index if not exists leads_platform_idx
  on public.leads (platform);

create index if not exists leads_created_at_idx
  on public.leads (created_at desc);

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at
before update on public.leads
for each row execute function public.set_updated_at();

alter table public.leads enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'leads'
      and policyname = 'allow anon insert leads'
  ) then
    create policy "allow anon insert leads"
    on public.leads
    for insert
    to anon
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'leads'
      and policyname = 'allow anon select leads'
  ) then
    create policy "allow anon select leads"
    on public.leads
    for select
    to anon
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'leads'
      and policyname = 'allow anon update leads'
  ) then
    create policy "allow anon update leads"
    on public.leads
    for update
    to anon
    using (true)
    with check (true);
  end if;
end $$;

select pg_notify('pgrst', 'reload schema');
